export class Student {
	constructor(
		private course_id: string,
		private firstchoice: number,
		private secondchoice: string,
		private fullname: string,
		private email: string,
		private mobile: number,
		private home_tel_number: number,
		private birthdate: string,
		private age: number,
		private gender: number,
		private home_address: string,
		private postcode: number,
		private guardin_name: string,
		private guardin_number: number,
		private pps_number: string,
		private student_status: number,
		private highest_award: string,
		private nationality_status: number,
		private nationality_info: string,
		private hse_medical_status: number,
		private school_name: string,
		private school_number: string,
		private school_leaving_year: number,
		private school_address: string,
		private leaving_certificate_school_id: number,
		private leaving_certificate_school_name: string,
		private leaving_certificate_school_number: string,
		private leaving_certificate_school_year: number,
		private leaving_certificate_school_address: string,
		private leaving_certificate_work_experience: string,
		private mode_status: number,
		private mode_info: string,
		private result_status: number,
		private other_certificate: string,
		private other_examination: string,
		private work_experience: string,
		private disability_condition: string,
		private disability_support: string,
		private disability_info: string,
		private course_reference: string,
		private first_ref_name	: string,
		private first_ref_number: number,
		private second_ref_name: string,
		private second_ref_number: number,
		private firstname: string,
		private surname: string,
		private signature: string,
		private written_reference_status: number,
		private cdetb_confirmation: number,
		private subscriber_status: number,
		private status: number = 1,
		private is_deleted: number = 0,
		private created_by: number = 1,
		private update_by: number = 1
	){}
}